import type { Address } from './address';
import type { Country } from './country';
import type { Destination } from './destination';
import type { Base, Nameable } from './types';
import type { Media } from './media';
import type { Agency } from './agency';
import type { Kind } from './category';

export type Advisor = Base &
	Nameable & {
		firstname?: string;
		lastname?: string;
		biography?: string;
		accept?: boolean;
		planningFee?: boolean;
		email?: string;
		phone_number?: string;
		cell_mobile?: string;
		whatsapp?: string;
		emergency?: string;
		phone_number_code?: string;
		cell_mobile_code?: string;
		whatsapp_code?: string;
		emergency_code?: string;
		initials?: string;
		alternateEmail?: string;
		linkedIn?: string;
		facebook?: string;
		joined_at?: string;
		twitter?: string;
		instagram?: string;
		pinterest?: string;
		active?: boolean;
		reference?: string;
		website?: string;
		timezone?: string;
		address?: Address;
		country?: Country;
		language1?: Kind;
		language2?: Kind;
		language3?: Kind;
		language4?: Kind;
		language5?: Kind;
		language6?: Kind;
		experiences?: Kind[];
		destinations?: Destination[];
		avatar?: Media;
		name?: string;
		experienceType1?: Kind;
		experienceType2?: Kind;
		experienceType3?: Kind;
		experienceType4?: Kind;
		experienceType5?: Kind;
		agency_uid: string;
		agency: Agency;
	};
