export const INVALID_DELAY_TIME = 3000; // ms
export const TIME_RESEND_EMAIL_FORGOT_PW = 10; // s
export const FIREBASE_EMAIL_EXIST_CODE = 'auth/email-already-in-use';
export const TIME_ZONES = [
	{ locale: 'America/Havana', gmt: '(GMT-05:00) Cuba' },
	{ locale: 'America/Bogota', gmt: '(GMT-05:00) Bogota, Lima, Quito, Rio Branco' },
	{ locale: 'America/Caracas', gmt: '(GMT-04:30) Caracas' },
	{ locale: 'America/Santiago', gmt: '(GMT-04:00) Santiago' },
	{ locale: 'America/La_Paz', gmt: '(GMT-04:00) La Paz' },
	{ locale: 'Atlantic/Stanley', gmt: '(GMT-04:00) Faukland Islands' },
	{ locale: 'America/Campo_Grande', gmt: '(GMT-04:00) Brazil' },
	{ locale: 'America/Goose_Bay', gmt: '(GMT-04:00) Atlantic Time (Goose Bay)' },
	{ locale: 'America/Glace_Bay', gmt: '(GMT-04:00) Atlantic Time (Canada)' },
	{ locale: 'America/St_Johns', gmt: '(GMT-03:30) Newfoundland' },
	{ locale: 'America/Araguaina', gmt: '(GMT-03:00) UTC-3' },
	{ locale: 'America/Montevideo', gmt: '(GMT-03:00) Montevideo' },
	{ locale: 'America/Miquelon', gmt: '(GMT-03:00) Miquelon, St. Pierre' },
	{ locale: 'America/Godthab', gmt: '(GMT-03:00) Greenland' },
	{ locale: 'America/Argentina/Buenos_Aires', gmt: '(GMT-03:00) Buenos Aires' },
	{ locale: 'America/Sao_Paulo', gmt: '(GMT-03:00) Brasilia' },
	{ locale: 'America/Noronha', gmt: '(GMT-02:00) Mid-Atlantic' },
	{ locale: 'Atlantic/Cape_Verde', gmt: '(GMT-01:00) Cape Verde Is.' },
	{ locale: 'Atlantic/Azores', gmt: '(GMT-01:00) Azores' },
	{ locale: 'Europe/Belfast', gmt: '(GMT) Greenwich Mean Time : Belfast' },
	{ locale: 'Europe/Dublin', gmt: '(GMT) Greenwich Mean Time : Dublin' },
	{ locale: 'Europe/Lisbon', gmt: '(GMT) Greenwich Mean Time : Lisbon' },
	{ locale: 'Europe/London', gmt: '(GMT) Greenwich Mean Time : London' },
	{ locale: 'Africa/Abidjan', gmt: '(GMT) Monrovia, Reykjavik' },
	{
		locale: 'Europe/Amsterdam',
		gmt: '(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna'
	},
	{
		locale: 'Europe/Belgrade',
		gmt: '(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague'
	},
	{ locale: 'Europe/Brussels', gmt: '(GMT+01:00) Brussels, Copenhagen, Madrid, Paris' },
	{ locale: 'Africa/Algiers', gmt: '(GMT+01:00) West Central Africa' },
	{ locale: 'Africa/Windhoek', gmt: '(GMT+01:00) Windhoek' },
	{ locale: 'Asia/Beirut', gmt: '(GMT+02:00) Beirut' },
	{ locale: 'Africa/Cairo', gmt: '(GMT+02:00) Cairo' },
	{ locale: 'Asia/Gaza', gmt: '(GMT+02:00) Gaza' },
	{ locale: 'Africa/Blantyre', gmt: '(GMT+02:00) Harare, Pretoria' },
	{ locale: 'Asia/Jerusalem', gmt: '(GMT+02:00) Jerusalem' },
	{ locale: 'Europe/Minsk', gmt: '(GMT+02:00) Minsk' },
	{ locale: 'Asia/Damascus', gmt: '(GMT+02:00) Syria' },
	{ locale: 'Europe/Moscow', gmt: '(GMT+03:00) Moscow, St. Petersburg, Volgograd' },
	{ locale: 'Africa/Addis_Ababa', gmt: '(GMT+03:00) Nairobi' },
	{ locale: 'Asia/Tehran', gmt: '(GMT+03:30) Tehran' },
	{ locale: 'Asia/Dubai', gmt: '(GMT+04:00) Abu Dhabi, Muscat' },
	{ locale: 'Asia/Yerevan', gmt: '(GMT+04:00) Yerevan' },
	{ locale: 'Asia/Kabul', gmt: '(GMT+04:30) Kabul' },
	{ locale: 'Asia/Yekaterinburg', gmt: '(GMT+05:00) Ekaterinburg' },
	{ locale: 'Asia/Tashkent', gmt: '(GMT+05:00) Tashkent' },
	{ locale: 'Asia/Kolkata', gmt: '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi' },
	{ locale: 'Asia/Katmandu', gmt: '(GMT+05:45) Kathmandu' },
	{ locale: 'Asia/Dhaka', gmt: '(GMT+06:00) Astana, Dhaka' },
	{ locale: 'Asia/Novosibirsk', gmt: '(GMT+06:00) Novosibirsk' },
	{ locale: 'Asia/Rangoon', gmt: '(GMT+06:30) Yangon (Rangoon)' },
	{ locale: 'Asia/Bangkok', gmt: '(GMT+07:00) Bangkok, Hanoi, Jakarta' },
	{ locale: 'Asia/Krasnoyarsk', gmt: '(GMT+07:00) Krasnoyarsk' },
	{ locale: 'Asia/Hong_Kong', gmt: '(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi' },
	{ locale: 'Asia/Irkutsk', gmt: '(GMT+08:00) Irkutsk, Ulaan Bataar' },
	{ locale: 'Australia/Perth', gmt: '(GMT+08:00) Perth' },
	{ locale: 'Australia/Eucla', gmt: '(GMT+08:45) Eucla' },
	{ locale: 'Asia/Tokyo', gmt: '(GMT+09:00) Osaka, Sapporo, Tokyo' },
	{ locale: 'Asia/Seoul', gmt: '(GMT+09:00) Seoul' },
	{ locale: 'Asia/Yakutsk', gmt: '(GMT+09:00) Yakutsk' },
	{ locale: 'Australia/Adelaide', gmt: '(GMT+09:30) Adelaide' },
	{ locale: 'Australia/Darwin', gmt: '(GMT+09:30) Darwin' },
	{ locale: 'Australia/Brisbane', gmt: '(GMT+10:00) Brisbane' },
	{ locale: 'Australia/Hobart', gmt: '(GMT+10:00) Hobart' },
	{ locale: 'Asia/Vladivostok', gmt: '(GMT+10:00) Vladivostok' },
	{ locale: 'Australia/Lord_Howe', gmt: '(GMT+10:30) Lord Howe Island' },
	{ locale: 'Etc/GMT-11', gmt: '(GMT+11:00) Solomon Is., New Caledonia' },
	{ locale: 'Asia/Magadan', gmt: '(GMT+11:00) Magadan' },
	{ locale: 'Pacific/Norfolk', gmt: '(GMT+11:30) Norfolk Island' },
	{ locale: 'Asia/Anadyr', gmt: '(GMT+12:00) Anadyr, Kamchatka' },
	{ locale: 'Pacific/Auckland', gmt: '(GMT+12:00) Auckland, Wellington' },
	{ locale: 'Etc/GMT-12', gmt: '(GMT+12:00) Fiji, Kamchatka, Marshall Is.' },
	{ locale: 'Pacific/Chatham', gmt: '(GMT+12:45) Chatham Islands' },
	{ locale: 'Pacific/Tongatapu', gmt: "(GMT+13:00) Nuku'alofa" },
	{ locale: 'Pacific/Kiritimati', gmt: '(GMT+14:00) Kiritimati' }
];
